---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
  - deployment.yml
  - service.yml
  - ingress.yml
  - secret.yml
  - configmaps

commonLabels:
  group: fhir-feature-test3