apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fhir-feature-test2-db-credentials
  namespace: apps
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: qa-vault
    kind: ClusterSecretStore
  target:
    name: fhir-feature-test2-db-credentials
    template:
      engineVersion: v2
      data:
        SPRING_DATASOURCE_USERNAME: "{{ .username }}"
        SPRING_DATASOURCE_PASSWORD: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: secret/cluster-qa/postgres/credentials/fhir-feature-test2
        property: username
    - secretKey: password
      remoteRef:
        key: secret/cluster-qa/postgres/credentials/fhir-feature-test2
        property: password